### ISSUE TITLE
Embed javascript engine and redesign plugin architecture

### ISSUE THREAD

**Issue by winterdl** [tachiyomiorg/tachiyomi-1.x#12]
I wish the app embed javascript engine, and redesign the plugin architecture, we do not using java plugin because of complexing of install process, we using javascript as plugin, then we could load script without installing any plugins, then we could parsing sources by javascript, the script engine embeded jsoup, then we could request and parser in javascript. The app will load script by context, the script will parsing html then return json object.

The plugin will redesign like this:

cmanga.com
 - home.js: list all tab list manga filter by some condition
 - detail.js: return json about one manga informatino
 - toc.js: return all index eposide...
 - chapter.js: return all content image of a chapter
 - search.js: input query, output json list all searched manga

when user chose a source, ex cmanga.com, the app will load home.js

- home.js will return json all tab list all manga filter by some condition

when user select one manga, the app will load detail.js, then if user tap indexing, the toc.js script will be loaded and run to get the json object of all eposides of the manga, when read a chapter, the chapter.js script will be run to parser and return json object about chapter detail....

**Comment by inorichi** [comment]
A Javascript might be implemented on top of the kotlin API, but I'm still not sure it's going to be implemented. Embedding a Javascript engine will affect APK size quite a lot, and you'll always be more limited than with a Kotlin extension. If you're worried about the current installation process you don't have to worry about it because they can be installed or updated silently now without requiring any user confirmation.

**Comment by winterdl** [comment]
I've used an app that use javascript engine as plugin engine, it's plugin engine works better than tachiyomi one, easy to write new plugin, don't need to compile to deploy, run as fast as java plugin, and the apk size still small.

You could read this plugins repo: https://github.com/Darkrai9x/vbook-extensions 
and app link: http://bit.ly/vbookapp , an app use for reading text novel and manga, it also support text to speech and export to epub.
The author of app come from Vietnam, I dont understand Vietnamese interface but I could change language to English and write plugin for myseft, it is very easy to write new plugin, the core support enough functions for me to add new source. Thanks to the author but I dont know why he didnt publish it to google play.

It is wonderful if you could support the plugin engine like the app. Thank you.

**Comment by CarlosEsco** [comment]
@winterdl can you explain how it works better? Besides the fact it seems you are familiar with js and not kotlin.

**Comment by CarlosEsco** [comment]
Also you linked a closed source(?) App. The extensions repo you provided provides nothing on how they are actually using the js in the app.

**Comment by winterdl** [comment]
I just suggest a new way to implement plugin engine, I used both apps, and I think the javascript plugin is better for me, if a source changed or add new source, I just add/edit  text files and reload.
