### ISSUE TITLE
Hiatus status 

### ISSUE THREAD

**Issue by zayin02** [tachiyomiorg/tachiyomi-1.x#17]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Currently Tachiyomi has these:
• Ongoing
• Completed 
• Unknown status 

The problem comes in when a book is on hiatus, it is normally set to unknown status even though the status is already known. Depending on the extention, if the hiatus isn't known then it should say "Unknown status".

Implementing this can help the reader understand why the manga may not be updating chapters. It could also be used for filtering.

**Comment by arkon** [comment]
I'll transfer this over to the 1.x project so we remember to have this in the rewritten models.

**Comment by ObserverOfTime** [comment]
Along with "hiatus" you could also add "cancelled".
