### ISSUE TITLE
Don't pluralize manga as mangas

### ISSUE THREAD

**Issue by CarlosEsco** [tachiyomiorg/tachiyomi-1.x#19]
Manga plural is manga so mangas just looks wrong.   MangaList, mangaMap etc

**Comment by inorichi** [comment]
I was always aware of this, but thought it was ok for code as it makes it easier to discern a list from a single item and keep the variable name short, but if everyone prefers `mangaList` I don't mind changing it.

**Comment by arkon** [comment]
I'm fine either way. We already intentionally spell things like `colour` wrong anyway.
